---
# Inline comments allowed
AWSTemplateFormatVersion: "2010-09-09"

Description: Testing template
Parameters:
  CreatedBy:
    Description: Created By Name
    Type: String
Resources:
  CloudFormationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: DevTestrole
      Description: IAM role to deploy resources from the AWS CodePipeline
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AdministratorAccess
      AssumeRolePolicyDocument:
        Statement:
            - Action: sts:AssumeRole
              Effect: Allow
              Principal:
                Service: [cloudformation.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Tags: 
        - Key: CreatedBy
          Value: !Ref CreatedBy      
      # MaxSessionDuration: Integer
      # PermissionsBoundary: String
